package it.polimi.ingswPSP35.commons;

public enum MessageID {
    NOTIFICATION,
    GETNUMBEROFPLAYERS,
    CHOOSE2DIVINITIES,
    CHOOSE3DIVINITIES,
    PICKDIVINITY,
    PERFORMACTION,
    UPDATE,
    PLACEWORKER,
    USERINFO,
    DIVINITIESCHOSEN,
    CHOOSECOLOUR,
    FINISHEDSETUP,
    DISCONNECTED
    //
}
